name: CD Production

on:
  pull_request_target:
    branches:
      - production
    types:
      - closed

jobs:
  run-ci:
    if: github.event.pull_request.merged == true
    name: Run Prod CI
    uses: ./.github/workflows/run-ci.yml
    secrets:
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}

  run-release:
    if: github.event.pull_request.merged == true
    name: Release Production
    uses: royfuwei/rf-devops/.github/workflows/_node-release-nx.yml@main
    needs: run-ci
    secrets:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}